apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
data:
  # Application metadata
  app.name: {{ .Values.app.name | quote }}
  app.version: {{ .Values.app.version | quote }}

  # Server configuration
  server.port: {{ .Values.server.port | quote }}
  server.readTimeout: {{ .Values.server.readTimeout | quote }}
  server.writeTimeout: {{ .Values.server.writeTimeout | quote }}
  server.idleTimeout: {{ .Values.server.idleTimeout | quote }}
  server.debug: {{ .Values.server.debug | quote }}

  # Storage configuration (non-sensitive)
  storage.endpoint: {{ .Values.storage.endpoint | quote }}
  storage.region: {{ .Values.storage.region | quote }}
  storage.bucket: {{ .Values.storage.bucket | quote }}
  storage.useSSL: {{ .Values.storage.useSSL | quote }}
  storage.urlExpiration: {{ .Values.storage.urlExpiration | quote }}
  storage.pathPrefix: {{ .Values.storage.pathPrefix | quote }}

  # Kafka configuration (non-sensitive)
  kafka.brokers: {{ join "," .Values.kafka.brokers | quote }}
  kafka.topic: {{ .Values.kafka.topic | quote }}
  kafka.securityProtocol: {{ .Values.kafka.securityProtocol | quote }}
  kafka.clientId: {{ .Values.kafka.clientId | quote }}
  kafka.batchSize: {{ .Values.kafka.batchSize | quote }}
  kafka.retries: {{ .Values.kafka.retries | quote }}

  # Upload configuration
  upload.maxUploadSize: {{ .Values.upload.maxUploadSize | quote }}
  upload.maxMemory: {{ .Values.upload.maxMemory | quote }}
  upload.tempDir: {{ .Values.upload.tempDir | quote }}
  upload.allowedTypes: {{ join "," .Values.upload.allowedTypes | quote }}
  upload.requireAuth: {{ .Values.upload.requireAuth | quote }}

  # Logging configuration
  logging.level: {{ .Values.logging.level | quote }}
  logging.format: {{ .Values.logging.format | quote }}
  logging.output: {{ .Values.logging.output | quote }}

  # Metrics configuration
  metrics.enabled: {{ .Values.metrics.enabled | quote }}
  metrics.path: {{ .Values.metrics.path | quote }}
  metrics.port: {{ .Values.metrics.port | quote }}