apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: insights-ros-ingress
data:
  # Application metadata
  app.name: {{ .Values.app.name | quote }}
  app.version: {{ .Values.app.version | quote }}

  # Server configuration
  server.port: {{ .Values.config.server.port | quote }}
  server.readTimeout: {{ .Values.config.server.readTimeout | quote }}
  server.writeTimeout: {{ .Values.config.server.writeTimeout | quote }}
  server.idleTimeout: {{ .Values.config.server.idleTimeout | quote }}
  server.debug: {{ .Values.config.server.debug | quote }}

  # Upload configuration
  upload.maxUploadSize: {{ .Values.config.upload.maxUploadSize | quote }}
  upload.maxMemory: {{ .Values.config.upload.maxMemory | quote }}
  upload.tempDir: {{ .Values.config.upload.tempDir | quote }}
  upload.allowedTypes: {{ .Values.config.upload.allowedTypes | quote }}
  upload.requireAuth: {{ .Values.config.upload.requireAuth | quote }}

  # Logging configuration
  logging.level: {{ .Values.config.logging.level | quote }}
  logging.format: {{ .Values.config.logging.format | quote }}
  logging.output: {{ .Values.config.logging.output | quote }}

  # Metrics configuration
  metrics.enabled: {{ .Values.config.metrics.enabled | quote }}
  metrics.path: {{ .Values.config.metrics.path | quote }}
  metrics.port: {{ .Values.config.metrics.port | quote }}