apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/name: minio
data:
  # MinIO server configuration
  MINIO_CONSOLE_ADDRESS: ":{{ .Values.minio.ports.console }}"
  MINIO_API_PORT: {{ .Values.minio.ports.api | quote }}
  
  # MinIO storage configuration
  MINIO_COMPRESS: "on"
  MINIO_COMPRESS_EXTENSIONS: ".pdf,.doc,.docx"
  MINIO_COMPRESS_MIME_TYPES: "application/pdf"
  
  # MinIO default buckets
  MINIO_DEFAULT_BUCKETS: {{ join "," .Values.minio.buckets | quote }}
  
  # MinIO console configuration
  MINIO_BROWSER_REDIRECT_URL: "http://localhost:{{ .Values.minio.ports.console }}"