apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: kafka
data:
  # Kafka broker configuration
  KAFKA_BROKER_ID: {{ .Values.kafka.broker.brokerId | quote }}
  KAFKA_NUM_NETWORK_THREADS: "3"
  KAFKA_NUM_IO_THREADS: "8"
  KAFKA_SOCKET_SEND_BUFFER_BYTES: "102400"
  KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
  KAFKA_SOCKET_REQUEST_MAX_BYTES: "104857600"
  
  # Log configuration
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_LOG_RETENTION_BYTES: "1073741824"
  KAFKA_LOG_SEGMENT_BYTES: "1073741824"
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
  
  # Cleanup policy
  KAFKA_LOG_CLEANUP_POLICY: "delete"
  
  # Topic configuration
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: {{ .Values.kafka.broker.autoCreateTopicsEnable | quote }}
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: {{ .Values.kafka.broker.offsetsTopicReplicationFactor | quote }}
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  
  # Performance tuning
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_MIN_INSYNC_REPLICAS: "1"