apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/name: zookeeper
data:
  # Zookeeper server configuration
  ZOOKEEPER_SERVER_ID: {{ .Values.kafka.zookeeper.serverId | quote }}
  ZOOKEEPER_CLIENT_PORT: {{ .Values.kafka.zookeeper.clientPort | quote }}
  ZOOKEEPER_TICK_TIME: "2000"
  ZOOKEEPER_INIT_LIMIT: "5"
  ZOOKEEPER_SYNC_LIMIT: "2"
  
  # Data and log directories
  ZOOKEEPER_DATA_DIR: "/var/lib/zookeeper/data"
  ZOOKEEPER_DATA_LOG_DIR: "/var/lib/zookeeper/log"
  
  # Performance tuning
  ZOOKEEPER_MAX_CLIENT_CNXNS: "60"
  ZOOKEEPER_MIN_SESSION_TIMEOUT: "4000"
  ZOOKEEPER_MAX_SESSION_TIMEOUT: "40000"
  ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: "3"
  ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "1"
  
  # Logging
  ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "INFO"
  ZOOKEEPER_LOG4J_PROP: "INFO,CONSOLE"