apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgresql
data:
  # PostgreSQL configuration
  POSTGRES_DB: {{ .Values.database.insights.name | quote }}
  POSTGRES_USER: {{ .Values.database.insights.username | quote }}
  PGDATA: "/var/lib/postgresql/data/pgdata"
  
  # Connection and authentication
  POSTGRES_HOST_AUTH_METHOD: "md5"
  POSTGRES_INITDB_ARGS: "--auth-host=md5"
  
  # Performance tuning
  POSTGRES_SHARED_BUFFERS: "256MB"
  POSTGRES_EFFECTIVE_CACHE_SIZE: "1GB"
  POSTGRES_MAINTENANCE_WORK_MEM: "64MB"
  POSTGRES_CHECKPOINT_COMPLETION_TARGET: "0.9"
  POSTGRES_WAL_BUFFERS: "16MB"
  POSTGRES_DEFAULT_STATISTICS_TARGET: "100"
  POSTGRES_RANDOM_PAGE_COST: "1.1"
  
  # Logging
  POSTGRES_LOG_DESTINATION: "stderr"
  POSTGRES_LOG_STATEMENT: "none"
  POSTGRES_LOG_MIN_DURATION_STATEMENT: "1000"
  
  # Connection limits
  POSTGRES_MAX_CONNECTIONS: "100"