{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ include "insights-ros-ingress.routeHost" . }}
  path: {{ .Values.route.path }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "insights-ros-ingress.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}