apiVersion: v1
kind: Service
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/name: zookeeper
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kafka.zookeeper.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "insights-ros-ingress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/name: zookeeper
