apiVersion: v1
kind: Service
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgresql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.insights.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "insights-ros-ingress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgresql
