apiVersion: v1
kind: Service
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: insights-ros-ingress
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "insights-ros-ingress.selectorLabels" . | nindent 4 }}