apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "insights-ros-ingress.fullname" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insights-ros-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/name: zookeeper
spec:
  serviceName: {{ include "insights-ros-ingress.fullname" . }}-zookeeper
  replicas: 1
  selector:
    matchLabels:
      {{- include "insights-ros-ingress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/name: zookeeper
  template:
    metadata:
      labels:
        {{- include "insights-ros-ingress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zookeeper
        app.kubernetes.io/name: zookeeper
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: zookeeper
          image: "{{ .Values.kafka.zookeeper.image.repository }}:{{ .Values.kafka.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: client
              containerPort: {{ .Values.kafka.zookeeper.clientPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "insights-ros-ingress.fullname" . }}-zookeeper
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: {{ .Values.kafka.zookeeper.clientPort | quote }}
            - name: ZOOKEEPER_SERVER_ID
              value: {{ .Values.kafka.zookeeper.serverId | quote }}
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper/data
          resources:
            {{- toYaml .Values.resources.zookeeper | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.global.storageClass }}
        resources:
          requests:
            storage: {{ .Values.kafka.zookeeper.storage.size }}